document.writeln('<iframe src=\"about:blank\" name=\"hidform7\" style=\"width:0px;height:0px;display:none\"></iframe>')
document.writeln('<script src=\"/ks_inc/common.js\"></script>')
document.writeln('<script src=\"/ks_inc/form_ck.js\"></script>')
document.writeln('<form name=\"myform7\" action=\"/plus/form/form.asp\" onSubmit=\"return(form_c(7));\"  target=\"hidform7\" method=\"post\"> ')
document.writeln('<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"1\">')
document.writeln('<input type=\"hidden\" value=\"Save\" name=\"action\"/>')
document.writeln('<input type=\"hidden\" value=\"7\" name=\"id\"/>')
document.writeln('<input type=\"hidden\" value=\"0\" name=\"m\"/>')
document.writeln('<input type=\"hidden\" value=\"0\" name=\"d\"/>')
document.writeln('<input type=\"hidden\" value=\"{$ToUserName}\" id=\"tousername\" name=\"tousername\"/>')
document.writeln('')
document.writeln('<tr class=\"tdbg\" style=\"float:left; \">')
document.writeln('<td style=\"width:380px;\"><input type=\"text\" maxlength=\"255\" class=\"upfile\" style=\"width:357px; height:42px; border:#ccc solid 1px;\" id=\"KS_na\" name=\"KS_na\" ')
document.writeln('value=\"\" ')
document.writeln('placeholder=\"Name\">')
document.writeln('<span class=\"formstrck7\" id=\"Name|%|KS_na|%|1\" style=\"display:none\"></span><font color=\"red\"> * </font></td>')
document.writeln('')
document.writeln('<td style=\"width:380px;\"><input type=\"text\" maxlength=\"255\" class=\"upfile\" style=\"width:357px; height:42px; border:#ccc solid 1px;\" id=\"KS_ph\" name=\"KS_ph\" value=\"\" ')
document.writeln('placeholder=\"Phone\">')
document.writeln('<span class=\"formstrck7\" id=\"Phone|%|KS_ph|%|1\" style=\"display:none\"></span><font color=\"red\"> * </font></td>')
document.writeln('</tr>')
document.writeln('')
document.writeln('<tr class=\"tdbg\" style=\"float:left;\">')
document.writeln('  <td style=\"width:380px;\"><input type=\"text\" maxlength=\"255\" class=\"upfile\" style=\"width:357px; height:42px; border:#ccc solid 1px;margin-top:20px;\" id=\"KS_am\" ')
document.writeln('name=\"KS_am\" ')
document.writeln('value=\"\" placeholder=\"Email\"><span class=\"formstrck7\" id=\"Email|%|KS_am|%|1\" style=\"display:none\"></span><font color=\"red\"> * </font></td>')
document.writeln('')
document.writeln('<td style=\"width:380px;\"><input type=\"text\" maxlength=\"255\" class=\"upfile\" style=\"width:357px; height:42px; border:#ccc solid 1px;margin-top:20px;\" id=\"KS_coun\" name=\"KS_coun\" ')
document.writeln('value=\"\" placeholder=\"Country\"></td>')
document.writeln('</tr>')
document.writeln('')
document.writeln(' <tr class=\"tdbg\" style=\"float:left; width:760px;\">')
document.writeln('  <td><input type=\"text\" maxlength=\"255\" class=\"upfile\" style=\"width:738px; height:90px; border:#ccc solid 1px; margin-top:20px;\" id=\"KS_mae\" name=\"KS_mae\" value=\"\" ')
document.writeln('placeholder=\"Message\">')
document.writeln('  <span class=\"formstrck7\" id=\"Message|%|KS_mae|%|1\" style=\"display:none\"></span><font color=\"red\"> * </font>  </td>')
document.writeln('</tr>')
document.writeln('<tr><td colspan=\"2\" class=\"subtdbg fr\" align=\"center\"><input type=\"submit\" value=\"Submit\" name=\"submit1\" class=\"sub\"></td></tr>')
document.writeln('</table>')
document.writeln('</form>')
document.writeln('')
